<a href="https://colab.research.google.com/github/vishnumurly/AppliedAI/blob/master/TF_102.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

#Constant

In [ ]:
x=tf.constant(1.)
print(x)

tf.Tensor(1.0, shape=(), dtype=float32)


In [ ]:
y=tf.constant([[5,2],[3,1]])
print(y)

tf.Tensor(
[[5 2]
 [3 1]], shape=(2, 2), dtype=int32)


In [ ]:
y.numpy()

array([[5, 2],
       [3, 1]], dtype=int32)

In [ ]:
print(tf.ones(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)


#Arithemetic

In [ ]:
ini_val=tf.random.normal(shape=(2,2))
a=tf.Variable(ini_val)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.2706231 ,  0.75031865],
       [ 0.2082442 , -2.1609743 ]], dtype=float32)>


In [ ]:
tf.random.uniform(shape=(2,2))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.01766491, 0.00575244],
       [0.9799454 , 0.96060693]], dtype=float32)>

In [ ]:
new_val=tf.random.normal(shape=(2,2))
a.assign(new_val)


<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 0.06717473, -0.6748119 ],
       [ 0.2887461 ,  0.22329181]], dtype=float32)>

In [ ]:
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_val[i,j]

a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.06717473, -0.6748119 ],
       [ 0.2887461 ,  0.22329181]], dtype=float32)>

In [ ]:
add_val=tf.random.uniform(shape=(2,2))
a.assign_add(add_val)
a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.740007  , -0.46507996],
       [ 1.0969245 ,  0.962925  ]], dtype=float32)>

In [ ]:
for i in range(2):
  for j in range(2):
    assert a[i,j]==new_val[i,j]+add_val[i,j]

a

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 0.740007  , -0.46507996],
       [ 1.0969245 ,  0.962925  ]], dtype=float32)>

In [ ]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))
c=a+b
c

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.2321918 , -3.2266402 ],
       [-0.01701093, -0.4482197 ]], dtype=float32)>

#Computing gradient

In [ ]:
a=tf.random.normal(shape=(2,2))
b=tf.random.normal(shape=(2,2))

with tf.GradientTape() as tape:
  tape.watch(a)
  c=tf.sqrt(tf.square(a)+tf.square(b))
  dc_da=tape.gradient(c,a)
  print(dc_da)



tf.Tensor(
[[ 0.8359754  -0.51363146]
 [ 0.53924215 -0.8819992 ]], shape=(2, 2), dtype=float32)


#Linear regression

Y=Wx+B, W=weight, B= bais vector 

In [ ]:
input_dim=2
output_dim=1
w=tf.Variable(tf.random.uniform(shape=(input_dim,output_dim)))
b=tf.Variable(tf.zeros(shape=(output_dim,)))

In [ ]:
b

<tf.Variable 'Variable:0' shape=(1,) dtype=float32, numpy=array([0.], dtype=float32)>